core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('pessoa/', views.PessoaCreateView.as_view(), name='pessoa'),
    path('endereco/', views.EnderecoCreateView.as_view(), name='endereco'),
]

formularios/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework import routers
from core.api.viewsets import PessoaViewSet, SalarioViewSet


pessoa = routers.DefaultRouter()
salario = routers.DefaultRouter()
pessoa.register(r'pessoas', PessoaViewSet)
salario.register(r'salarios', SalarioViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('api/', include(pessoa.urls)),
    path('api/', include(salario.urls))
]

core/models.py
from django.db import models


# Create your models here.
class Pessoa(models.Model):
    nome = models.CharField(max_length=250)
    cpf = models.CharField(unique=True, max_length=14)
    salario = models.DecimalField(max_digits=20, decimal_places=2)

    class Meta:
        verbose_name = 'Pessoa'
        verbose_name_plural = 'Pessoas'

    def __str__(self):
        return self.nome


class Endereco(models.Model):
    logradouro = models.CharField(max_length=200)
    numero = models.IntegerField()
    bairro = models.CharField(max_length=200)
    cidade = models.CharField(max_length=200)
    estado = models.CharField(max_length=200)
    pessoa = models.ForeignKey(
        Pessoa,
        on_delete=models.CASCADE,
        related_name='enderecos'
    )

    class Meta:
        verbose_name = 'Endereço'

    def __str__(self):
        return self.pessoa.nome

core/forms.py
from django import forms
from django.contrib.auth.models import User

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Layout, Row
from validate_docbr import CPF

from .models import Pessoa, Endereco


class PessoaForm(forms.ModelForm):

    class Meta:
        model = Pessoa
        fields = '__all__'
        labels = {
            'cpf': 'CPF'
        }
        localized_fields = ('salario',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Div('nome', css_class="col-6"),
                Div('cpf', css_class="col-6"),
                Div('salario', css_class="col-6"),
            ),
        )

    def clean_cpf(self):
        cpf = self.cleaned_data.get('cpf')

        validate_cpf = CPF()
        if not validate_cpf.validate(cpf):
            raise forms.ValidationError('O CPF é invalido')

        return cpf


class EnderecoForm(forms.ModelForm):

    class Meta:
        model = Endereco
        fields = '__all__'
        widgets = {
            'pessoa': forms.RadioSelect()
        }

core/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import PessoaForm, EnderecoForm
from .models import Pessoa, Endereco
# Create your views here.


class PessoaCreateView(CreateView):
    model = Pessoa
    template_name = "core/pessoa.html"
    form_class = PessoaForm
    success_url = reverse_lazy('pessoa')


class EnderecoCreateView(CreateView):
    model = Endereco
    template_name = "core/endereco.html"
    form_class = EnderecoForm
    success_url = reverse_lazy('endereco')

core/templates/core/endereco.html
{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

{% for message in messages %}
    {{ message }}
{% endfor %}

<div class="col-6">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Salvar">
    </form>
</div>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

core/templates/core/pessoa.html
{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
{% for message in messages %}
    {{ message }}
{% endfor %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% crispy form %}
<input type="submit" value="Salvar">
</form>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
<script>
    $(function(){
        $('#id_salario').mask('000,00', {reverse: true})
    })
</script>